GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/6797d1bd8aa105a48a9e7fba

### 

DELETE http://localhost:3001/api/persons/6797e97570e5121b556e47f8

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "new persons",
    "number": 123
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "next",
    "number": "123-45678"
}

###

PUT http://localhost:3001/api/persons/679901153a3ce432eef4048e
Content-Type: application/json

{
    "name": "james",
    "number": "12-345678"
}